spring:
  profiles:
    active: dev
---
server:
   port: 8888
spring:
   profiles: dev 
   application:
      name: feign-consumer-dev
   thymeleaf:
      cache:false
eureka:
   client:
      service-url:
         defaultZone: http://localhost:9001/eureka/
feign:
   hystrix:
      enabled: true
ribbon:
   ReadTimeout: 60000
   ConnectTimeout: 60000
   eureka:
      enabled: true
---
server:
   port: 8888
spring:
   profiles: test 
   application:
      name: feign-consumer-test
   thymeleaf:
      cache:false
eureka:
   client:
      service-url:
         defaultZone: http://localhost:9001/eureka/
feign:
   hystrix:
      enabled: true
ribbon:
   ReadTimeout: 60000
   ConnectTimeout: 60000
   eureka:
      enabled: true