spring:
  profiles:
    active: dev
---
spring:
   profiles: dev
   application:
      name: feign-consumer-zuul-dev 
---
spring:
   profiles: test
   application:
      name: feign-consumer-zuul-test